version: "3.7"
services:
  kafka_perfo:
    image: "kafka_perfo:latest"
    depends_on:
      - kafka-broker
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../src/:/workspace/
    # command: bash
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: di_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka-broker:
    container_name: di_broker
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-broker:9092, OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092, OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: di_kafdrop
    restart: unless-stopped
    ports:
      - "9002:9000"
    depends_on:
      - kafka-broker
    environment:
      KAFKA_BROKERCONNECT: "kafka-broker:9092"

networks:
  default:
    external:
      name: $NETWORK_NAME